package com.bhagya.commerce.common.error;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INVALID_CREDENTIALS,
    INVALID_OTP,
    ORDER_NOT_FOUND,
    ORDER_ACCESS_DENIED,
    STORE_NOT_FOUND,
    STORE_ACCESS_DENIED,
    PRODUCT_NOT_FOUND,
    INSUFFICIENT_STOCK,
    PAYMENT_FAILED,
    IDEMPOTENCY_VIOLATION,
    RATE_LIMIT_EXCEEDED
}
