package com.bhagya.commerce.analytics.domain;

public enum AnalyticsEventType {
    // Customer events
    SESSION_STARTED,
    PRODUCT_VIEWED,
    SEARCH_PERFORMED,
    CATEGORY_VIEWED,
    COLLECTION_VIEWED,
    PRODUCT_ADDED_TO_CART,
    PRODUCT_REMOVED_FROM_CART,
    WISHLIST_ADDED,
    WISHLIST_REMOVED,
    CHECKOUT_STARTED,
    ADDRESS_SELECTED,
    DELIVERY_SELECTED,
    PAYMENT_STARTED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    ORDER_CREATED,
    ORDER_DELIVERED,
    PRODUCT_REVIEWED,

    // Merchant events
    MERCHANT_LOGIN,
    STORE_VIEWED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_ARCHIVED,
    INVENTORY_UPDATED,
    ORDER_VIEWED,
    ORDER_UPDATED,
    STORE_UPDATED,
    CAMPAIGN_CREATED,

    // Platform events
    USER_REGISTERED,
    STORE_CREATED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_CHANGED,
    SUPPORT_TICKET_CREATED
}
